### ISSUE TITLE
Typo Issue! :D

### ISSUE THREAD

**Issue by wangseung** [adxcorp/ADXLibrary_iOS_Release#2]
https://github.com/adxcorp/ADXLibrary_iOS_Release/blob/e1a6cedf0f56590a38bbb480b159905fccda1196/ios/ADXLibrary.framework/Headers/ADXRewardedAd.h#L44-L45

rewwaredAd => rewardedAd

**Comment by adxcorp** [comment]
This has been fixed in the latest SDK v2.1.6. Thanks for bringing it to our attention!
